spring:
  kafka:
    bootstrap-servers: 43.203.240.20:9092
  application:
    name: NOTIFICATION-SERVICE
  config:
    import:
      - optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: ${GMAIL_MAIL_HOST}
    port: ${GMAIL_MAIL_PORT}
    username: ${GMAIL_MAIL_USER}
    password: ${GMAIL_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    database: mysql
server:
  port: 8082

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

