spring:
  application:
    name: NOTIFICATION-SERVICE
  config:
    import:
      - optional:file:.env[.properties]
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 2

  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: ${GMAIL_MAIL_HOST}
    port: ${GMAIL_MAIL_PORT}
    username: ${GMAIL_MAIL_USER}
    password: ${GMAIL_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: mysql
server:
  port: 8082

logging:
  level:
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

slack:
  webhook:
    url: https://hooks.slack.com/services/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

