server:
  port: 7070
spring:
  application:
    name: FRAME-CHECKMATE-GATEWAY
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
      routes:
        - id: card-service
          uri: http://localhost:7070
          predicates:
            - Path=/card/**
          filters:
            - AuthorizationHeaderFilter
        - id: member-service-post
          uri: http://localhost:8080
          predicates:
            - Path=/member/**
            - Method=POST
        - id: member-service-get
          uri: http://localhost:8080
          predicates:
            - Path=/member/**
            - Method=GET
          filters:
            - AuthorizationHeaderFilter
        - id: project-service
          uri: http://localhost:8080
          predicates:
            - Path=/project/**
          filters:
            - AuthorizationHeaderFilter
        - id: notification-service
          uri: http://localhost:9090
          predicates:
            - Path=/notification/**
          filters:
            - AuthorizationHeaderFilter


jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
