server:
  port: 7070
spring:
  application:
    name: FRAME-CHECKMATE-GATEWAY
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
      routes:
        - id: card-service
          uri: http://localhost:7070
          predicates:
            - Path=/card/**
        - id: member-service
          uri: http://localhost:8080
          predicates:
            - Path=/member/**
        - id: project-service
          uri: http://localhost:8080
          predicates:
            - Path=/project/**
        - id: notification-service
          uri: http://localhost:9090
          predicates:
            - Path=/notification/**


jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb