services:
  db:
    image: mysql
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    restart: always
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=ec2-kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=43.203.240.20:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=43.203.240.20:2181
