pipeline {
    agent any
    environment {
        DOCKER = 'sudo docker'
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('Build image') {
            steps {
                sh 'ls -al'
                dir('/var/jenkins_home/workspace/member-service/backend/user-service') {
                    sh 'ls -al'
                    sh 'chmod +x ./gradlew'
                    sh './gradlew build -x test'
                    sh 'docker build -t sukkong/member-service:latest .'
                    sh 'docker push sukkong/member-service'
                }
                echo 'Build image and Push f...'
            }
        }

        stage('Run New Image') {
            steps {
                sh '''
                    ssh ubuntu@ip-172-26-0-247 '
                    cd /home/ubuntu/member-service
                    docker-compose up -d
                '''
            }
        }
    }
}